name: 'MineyCrafta'
version: 0.0.1
description: THE MINE. THE CRAFT. DO IT.
author: iconmaster <crazybonesj@yahoo.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- dart_to_js_script_rewriter
